<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Table;
use Illuminate\Http\Request;
use SimpleSoftwareIO\QrCode\Facades\QrCode;
use BaconQrCode\Renderer\ImageRenderer;
use BaconQrCode\Renderer\Image\SvgImageBackEnd;
use BaconQrCode\Renderer\RendererStyle\RendererStyle;
use BaconQrCode\Writer;

class TableController extends Controller
{
    public function index()
    {
        $tables = Table::latest()->get();
        return view('admin.tables.index', compact('tables'));
    }

    public function create()
    {
        return view('admin.tables.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'number' => 'required|string|unique:tables,number',
        ]);

        // Create table - secure token will be auto-generated by model
        $table = Table::create([
            'number' => $request->number,
            'status' => 'available',
        ]);

        // Update QR code URL to use secure token
        $table->update([
            'qr_code' => $table->getSecureUrl(),
        ]);

        return redirect()->route('admin.tables.index')->with('success', 'Table created successfully.');
    }

    public function destroy(Table $table)
    {
        // Check if table has any orders
        if ($table->orders()->exists()) {
            return redirect()
                ->route('admin.tables.index')
                ->with('error', 'Cannot delete table with existing orders. Please delete or reassign orders first.');
        }

        $table->delete();
        return redirect()->route('admin.tables.index')->with('success', 'Table deleted successfully.');
    }
    
    public function showQr(Table $table)
    {
        // Display QR Code inline (for preview)
        $renderer = new ImageRenderer(
            new RendererStyle(400),
            new SvgImageBackEnd()
        );
        $writer = new Writer($renderer);
        $qr = $writer->writeString($table->qr_code);
        
        return response($qr)
            ->header('Content-Type', 'image/svg+xml');
    }
    
    public function printQr(Table $table)
    {
        // Show print-friendly page
        return view('admin.tables.print', compact('table'));
    }
    
    public function downloadQr(Table $table)
    {
        // Use BaconQrCode directly with SVG backend (no extension dependencies)
        $renderer = new ImageRenderer(
            new RendererStyle(300),
            new SvgImageBackEnd()
        );
        $writer = new Writer($renderer);
        $qr = $writer->writeString($table->qr_code);
        
        return response($qr)
            ->header('Content-Type', 'image/svg+xml')
            ->header('Content-Disposition', 'attachment; filename="qrcode-table-' . $table->number . '.svg"');
    }

    public function clear(Table $table)
    {
        // Cancel all active orders for this table for today
        $activeOrders = \App\Models\Order::where('table_id', $table->id)
            ->whereIn('status', ['pending', 'confirmed', 'preparing', 'ready'])
            ->whereDate('created_at', now()->today())
            ->get();

        foreach ($activeOrders as $order) {
            $order->update([
                'status' => 'cancelled',
                'payment_status' => 'failed'
            ]);
            // Restore stock if needed
            $order->restoreStock();
        }

        // Rotate token and reset status
        $table->rotateToken();

        return redirect()->route('admin.tables.index')->with('success', "Meja {$table->number} berhasil dikosongkan.");
    }
}
